### ISSUE TITLE
[PROPOSAL] Option API

### ISSUE THREAD

**Issue by hadihammurabi** [goreq/goreq#1]
Sending request with variadic option parameters.

Example:
* `goreq.WithHeaders`
* `goreq.WithHooks`

From this
```go
goreq.Get("https://api.products.com/entities", nil)
```

To this
```go
goreq.Get(
  "https://api.products.com/entities",
  goreq.WithHeaders(map[string]string{
    "authorization": "Bearer tttttooookkkeeeennnnnn",
  }),
)
```

**Comment by ashwin-m** [comment]
Hi @hadihammurabi , 

just to confirm the behaviour, what you are looking for is this:
- if `goreq.WithHeaders` is passed in options, then add all headers to the request
- if `goreq.WithHooks` is passed in options, then run the function passed in the parameters before making request.

CMIIW

**Comment by hadihammurabi** [comment]
> Hi @hadihammurabi ,
> 
> just to confirm the behaviour, what you are looking for is this:
> 
> * if `goreq.WithHeaders` is passed in options, then add all headers to the request
> * if `goreq.WithHooks` is passed in options, then run the function passed in the parameters before making request.
> 
> CMIIW

Yes, something like that @ashwin-m .
In general, options sent using that way.
Any options i mean.

Headers and hooks just an example.

**Comment by ashwin-m** [comment]
Okay, I should be able to work on this.
Do you happen to have CONTRIBUTING.md file with contribution guidelines to your repo?

I am not sure how you want me to merge code in to your repo

**Comment by hadihammurabi** [comment]
> Okay, I should be able to work on this. Do you happen to have CONTRIBUTING.md file with contribution guidelines to your repo?
> 
> I am not sure how you want me to merge code in to your repo

Sure, i will make it ASAP

**Comment by hadihammurabi** [comment]
Hi, @ashwin-m.

Since no interaction any more, i will take this issue my self.
Thanks.
