### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by hadihammurabi** [goreq/goreq#4]
**Is your feature request related to a problem? Please describe.**
In a way to be production ready, this library should be tested.
Currently, testing is available but needs more coverage.
At least 80% or more.

**Describe the solution you'd like**
Write more unit test scripts to increase testing coverage.

**Additional context**
Current unit test result using `go test -v -cover ./...` command:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/16364286/193857033-c7c89687-c40f-405e-9d66-4fb7fed66d14.png">

**Comment by GaruGaru** [comment]
Added unit tests for both `option` and `response` in #5
